apiVersion: v2
name: extensionlib
description: Helm library for Steadybit extensions.
type: library
version: 1.2.1
maintainers:
  - email: daniel.reuter@steadybit.com
    name: reuda
  - email: ansgar.schulte@steadybit.com
    name: ansgarschulte
